FROM python:3.9-slim

# Set working directory
WORKDIR /usr/src/app

# Copy all the current directory contents to the container
COPY . .

# Install dependencies
RUN pip install confluent-kafka

# Run the producer.py script
CMD ["python", "producer.py"]
